apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-api-deplopyment
spec:
  selector:
    matchLabels:
      app: translation-api-pod
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: translation-api-pod
    spec:
      containers:
        - image: vmalashkov/translation-api-service
          imagePullPolicy: Always
          name: translation-api
          ports:
            - containerPort: 8080