version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: ["server"]
    environment:
      - KAFKA_URLS=kafka_1:9092,kafka_2:9092
      - REDIS_URL=redis://redis:6379
    ports:
      - 8080:80
  translation:
    build:
      context: .
      dockerfile: translation/Dockerfile
      args:
        - TRANSLATION_CODE=en-ru
    command: ["server"]
    environment:
      - TORCH_DEVICE=cuda:0
      - TRANSLATION_CODE=en-ru
      - KAFKA_URLS=kafka_1:9092,kafka_2:9092
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka_1:
    image: bitnami/kafka:2
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data_1:/bitnami
  kafka_2:
    image: bitnami/kafka:2
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data_2:/bitnami
  redis:
    image: redis:6.2
  locust-master:
    build:
      context: .
      dockerfile: translation_perf/Dockerfile
    ports:
     - "8089:8089"
    command: -f /usr/src/app/main.py --master -H http://api:80
  locust-worker:
    deploy:
      replicas: 8
    build:
      context: .
      dockerfile: translation_perf/Dockerfile
    volumes:
      - ./:/mnt/locust
    command: -f /usr/src/app/main.py --worker --master-host locust-master
volumes:
  kafka_data_1:
    driver: local
  kafka_data_2:
    driver: local
  zookeeper_data:
    driver: local
