version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./translation-api/Dockerfile
    command: ["server"]
    ports:
      - 8080:80
    environment:
      - TORCH_DEVICE=cuda:0
      - TRANSLATION_MODEL_CODE=en-ru
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  locust-master:
    build:
      context: .
      dockerfile: ./translation-api-perf/Dockerfile
    ports:
     - "8089:8089"
    command: -f /usr/src/app/main.py --master -H http://api:80
  locust-worker:
    build:
      context: .
      dockerfile: ./translation-api-perf/Dockerfile
    volumes:
      - ./:/mnt/locust
    command: -f /usr/src/app/main.py --worker --master-host locust-master
