version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: ./translation-api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - XRAY=true
  xray-aws-xray:
    image: namshi/aws-xray
    ports:
      - 2000:2000/udp
    environment:
      - AWS_REGION=eu-central-1
    volumes:
      - ~/.aws/:/root/.aws/:ro
  perf:
    build:
      context: .
      dockerfile: ./translation-api-perf/Dockerfile
    ports:
      - 8089:8089
    environment:
      - TARGET_HOST=http://api:8080
