version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: ./translation-api/Dockerfile
    ports:
      - 8080:8080
  aws:
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    volumes:
      - ./infrastructure:/home/infrastructure