version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: ./translation-api/Dockerfile
    ports:
      - 8080:8080
  perf:
    build:
      context: .
      dockerfile: ./translation-api-perf/Dockerfile
    ports:
      - 8089:8089
    environment:
      - TARGET_URL=http://api:8080