apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-api-deployment
spec:
  selector:
    matchLabels:
      app: translation-api-pod
  replicas: {{ .Values.workers.replicaCount }}
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: translation-api-pod
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: translation-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: TRANSLATION_MODEL_CODE
              value: "{{ .Values.config.translationModelCode }}"
