apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-api-deployment
spec:
  selector:
    matchLabels:
      app: translation-api-pod
  replicas: {{ .Values.workers.replicaCount }}
#  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: translation-api-pod
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: translation-api
          ports:
            - containerPort: 80
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.workers.gpu }}
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          env:
            - name: TRANSLATION_MODEL_CODE
              value: "{{ .Values.config.translationModelCode }}"
          startupProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 80
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 80
            periodSeconds: 20
            failureThreshold: 3
