name: CICD

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'develop'
  release:
    types:
      - 'created'

jobs:
  test-api:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7.x", "3.8.x"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed by codecov.io

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test suite
        run: pip install -r cicd/test_requirements.txt

      - name: Install APIpackages
        run: pip install -r api/requirements.txt

      - name: Run tests
        run: py.test --cov=translation --cov-report=xml api/tests/

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml

  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0

  release-api-docker:
    runs-on: "ubuntu-latest"
    needs:
      - test-api
      - checks
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build API image
        run: |
          docker build \
            -f api/Dockerfile \
            -t vmalashkov/translation-api:${{ steps.vars.outputs.tag }} .
      - name: Push API image
        run: |
          docker push vmalashkov/translation-api:${{ steps.vars.outputs.tag }}

  release-translation-docker:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        language-code: ["en-ru", "ru-en"]
    needs:
      - test-api
      - checks
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build translation image
        run: |
          docker build \
            -f translation/Dockerfile \
            -t vmalashkov/translation-api-service:${{ matrix.language-code }}-${{ steps.vars.outputs.tag }} .
      - name: Push translation image
        run: |
          docker push vmalashkov/translation-api-service:${{ matrix.language-code }}-${{ steps.vars.outputs.tag }}

  release-perf-docker:
    runs-on: "ubuntu-latest"
    needs:
      - test-api
      - checks
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build locust image
        run: |
          docker build \
            -f translation_perf/Dockerfile \
            -t vmalashkov/translation-api-perf:${{ steps.vars.outputs.tag }} .
      - name: Push locust image
        run: |
          docker push vmalashkov/translation-api-perf:${{ steps.vars.outputs.tag }}
