name: Tests

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  test-api:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7.x", "3.8.x", "3.9.x"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      PARALLEL: "true"
      COVERAGE: "true"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed by codecov.io

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test suite
        shell: bash -l {0}
        run: pip install -r cicd/test_requirements.txt

      - name: Install app packages
        shell: bash -l {0}
        run: pip install -r translation-api/requirements.txt

      - name: Run tests
        shell: bash -l {0}
        run: py.test --cov=translation-api --cov-report=xml translation-api/tests/

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml